_extends: .github
repository:
  name: overridable-prompts
  description: Inquirer prompts that can be overriden with provided answers
  homepage: 'https://npm.im/@form8ion/overridable-prompts'
  private: false
